require("dotenv").config();
const express=require("express");
const cors=require("cors");
const path=require("path");
const {createClient}=require("@supabase/supabase-js");

const app=express();
const PORT=Number(process.env.PORT||3000);
const SITE_DIR=path.join(__dirname,"SITE");
const SUPABASE_URL=process.env.SUPABASE_URL;
const SUPABASE_KEY=process.env.SUPABASE_SECRET_KEY;
if(!SUPABASE_URL||!SUPABASE_KEY){console.error("ERRO: configure SUPABASE_URL e SUPABASE_SECRET_KEY no Render/.env");process.exit(1)}
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
app.set("trust proxy",1);app.use(cors());app.use(express.json({limit:"100kb"}));app.use(express.urlencoded({extended:true,limit:"100kb"}));app.use(express.text({type:"text/plain",limit:"100kb"}));app.use(express.static(SITE_DIR,{maxAge:0}));

let esp32={conectado:false,ultimoContato:null,ip:null};
let rfidEvent={nova:false,id:0,uid:null,tipo:"idle",modo:"idle",mensagem:"Passe a tag do funcionário.",funcionario:null,equipamento:null,equipamentos:[],equipamentoRecebido:null,equipamentoEsperado:null,box:null,momento:0};
let fluxo={modo:"idle",funcionario:null,acao:null,equipamentoSelecionado:null,expiraEm:0};
let cadastroRFID={ativo:false,tipo:null,expiraEm:0};
let ultimaLeitura={uid:null,momento:0};

const agora=()=>new Date().toISOString();
const texto=(v,f="")=>v==null?f:String(v);
const uid=(v)=>texto(v).toUpperCase().replace(/[^A-Z0-9]/g,"");
const status=(v)=>texto(v).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const erroMsg=e=>e?.message||String(e);
function erroResposta(res,e,codigo=500){console.error(e);return res.status(codigo).json({sucesso:false,erro:erroMsg(e)});}
function publicar(d){rfidEvent={nova:true,id:Date.now(),uid:d.uid||null,tipo:d.tipo||"idle",modo:d.modo||"idle",mensagem:d.mensagem||"",funcionario:d.funcionario||null,equipamento:d.equipamento||null,equipamentos:d.equipamentos||[],equipamentoRecebido:d.equipamentoRecebido||null,equipamentoEsperado:d.equipamentoEsperado||null,box:d.box??null,momento:Date.now()};return rfidEvent;}
function limparFluxo(){fluxo={modo:"idle",funcionario:null,acao:null,equipamentoSelecionado:null,expiraEm:0}}
function expirar(){if(fluxo.expiraEm&&Date.now()>fluxo.expiraEm)limparFluxo();if(cadastroRFID.expiraEm&&Date.now()>cadastroRFID.expiraEm)cadastroRFID={ativo:false,tipo:null,expiraEm:0}}
function corpoRFID(req){if(req.body&&typeof req.body==="object")return req.body;if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return {uid:req.body}}}return {}}

async function buscarFuncionarioPorUID(u){const r=await supabase.from("funcionarios").select("*").eq("uid_tag_pessoal",u).maybeSingle();if(r.error)throw r.error;return r.data||null}
async function buscarEquipamentoPorUID(u){const r=await supabase.from("equipamentos").select("*").eq("uid_tag",u).maybeSingle();if(r.error)throw r.error;return r.data||null}
async function ativosFuncionario(id){const r=await supabase.from("emprestimos").select("*").eq("funcionario_id",id).is("data_devolucao",null).order("id",{ascending:false});if(r.error)throw r.error;return r.data||[]}
async function ativoEquipamento(id){const r=await supabase.from("emprestimos").select("*").eq("equipamento_id",id).is("data_devolucao",null).order("id",{ascending:false}).limit(1);if(r.error)throw r.error;return r.data?.[0]||null}
async function equipamentos(){const r=await supabase.from("equipamentos").select("*").order("id",{ascending:true});if(r.error)throw r.error;return r.data||[]}
async function boxOcupada(box,ignorar=null){if(box==null||box==="")return false;const r=await supabase.from("equipamentos").select("id").eq("box_id",Number(box));if(r.error)throw r.error;return (r.data||[]).some(x=>Number(x.id)!==Number(ignorar))}
async function disponiveis(){const all=await equipamentos();return all.filter(e=>status(e.status)==="disponivel")}
async function enriquecer(rows){const fids=[...new Set(rows.map(x=>x.funcionario_id).filter(Boolean))],eids=[...new Set(rows.map(x=>x.equipamento_id).filter(Boolean))];const fm={},em={};if(fids.length){const r=await supabase.from("funcionarios").select("*").in("id",fids);if(r.error)throw r.error;(r.data||[]).forEach(x=>fm[x.id]=x)}if(eids.length){const r=await supabase.from("equipamentos").select("*").in("id",eids);if(r.error)throw r.error;(r.data||[]).forEach(x=>em[x.id]=x)}return rows.map(x=>({...x,funcionario:fm[x.funcionario_id]||null,equipamento:em[x.equipamento_id]||null}))}
async function verificarUID(u){const f=await buscarFuncionarioPorUID(u);if(f)return{encontrado:true,categoria:"funcionario",registro:f};const e=await buscarEquipamentoPorUID(u);if(e)return{encontrado:true,categoria:"equipamento",registro:e};return{encontrado:false}}

async function corrigirBoxesDuplicadas(){
 try{const all=await supabase.from("equipamentos").select("id,nome,box_id").order("id",{ascending:true});if(all.error)throw all.error;const usados=new Set();let proxima=1;for(const e of all.data||[]){let b=Number(e.box_id);if(!Number.isInteger(b)||b<1||usados.has(b)){while(usados.has(proxima))proxima++;b=proxima;await supabase.from("equipamentos").update({box_id:b}).eq("id",e.id);console.log(`Box ajustada: ${e.nome||e.id} -> Box ${b}`)}usados.add(b);proxima=Math.max(proxima,b+1)}}catch(e){console.error("Aviso ao verificar boxes:",e.message)}}

app.get("/",(req,res)=>res.sendFile(path.join(SITE_DIR,"index.html")));
app.get("/cadastro",(req,res)=>res.sendFile(path.join(SITE_DIR,"cadastro.html")));
app.get("/controle",(req,res)=>res.sendFile(path.join(SITE_DIR,"controle.html")));
app.get("/health",(req,res)=>res.json({sucesso:true,servidor:"online",banco:"Supabase",horario:agora()}));
app.get("/teste",(req,res)=>res.json({sucesso:true,mensagem:"Servidor RFID funcionando!",banco:"Supabase",esp32}));
app.get("/api/status",(req,res)=>res.json({sucesso:true,esp32,rfid:rfidEvent,fluxo}));
app.get("/api/esp32/status",(req,res)=>{const t=esp32.ultimoContato?Date.parse(esp32.ultimoContato):0;res.json({sucesso:true,conectado:!!t&&(Date.now()-t<30000),ultimoContato:esp32.ultimoContato,ip:esp32.ip})});
app.post("/api/esp32/online",(req,res)=>{const b=corpoRFID(req);esp32={conectado:true,ultimoContato:agora(),ip:texto(b.ip).trim()||null};res.json({sucesso:true,mensagem:"ESP32 conectado ao servidor",horario:esp32.ultimoContato})});

app.post("/api/esp32/rfid",async(req,res)=>{
 try{
  const b=corpoRFID(req);const u=uid(b.uid??b.UID??b.uid_tag??b.tag??b.rfid??b["UID da tag"]);if(!u)return res.status(400).json({sucesso:false,erro:"UID não informado."});
  esp32.conectado=true;esp32.ultimoContato=agora();if(b.ip)esp32.ip=texto(b.ip);const leitor=texto(b.leitor??b.reader,"entrada");console.log(`RFID ${u} | leitor=${leitor}`);expirar();
  if(ultimaLeitura.uid===u&&Date.now()-ultimaLeitura.momento<1000)return res.json({sucesso:true,repetida:true,uid:u,mensagem:"Leitura repetida ignorada."});ultimaLeitura={uid:u,momento:Date.now()};
  if(cadastroRFID.ativo&&Date.now()<cadastroRFID.expiraEm){const ex=await verificarUID(u);if(ex.encontrado){cadastroRFID={ativo:false,tipo:null,expiraEm:0};const ev=publicar({uid:u,tipo:"tag_ja_cadastrada",modo:"cadastro",mensagem:`Esta tag já está cadastrada como ${ex.categoria}: ${ex.registro.nome}.`});return res.status(409).json({sucesso:false,...ev})}cadastroRFID={ativo:false,tipo:null,expiraEm:0};const ev=publicar({uid:u,tipo:"cadastro_tag",modo:"cadastro",mensagem:"Tag lida com sucesso. UID preenchido."});return res.json({sucesso:true,...ev})}

  if(fluxo.modo==="aguardando_tag_retirada"||fluxo.modo==="aguardando_devolucao"){
   const eq=await buscarEquipamentoPorUID(u);if(!eq){const ev=publicar({uid:u,tipo:"tag_nao_cadastrada",modo:fluxo.modo,mensagem:"Essa tag não está cadastrada como equipamento. Passe a tag correta."});return res.status(404).json({sucesso:false,...ev})}
   const esperado=fluxo.equipamentoSelecionado;if(!esperado||Number(eq.id)!==Number(esperado.id)){const ev=publicar({uid:u,tipo:"objeto_incorreto",modo:fluxo.modo,mensagem:`Tag incorreta. Você selecionou "${esperado?.nome||"o equipamento"}". Passe a tag dele.`,funcionario:fluxo.funcionario,equipamento:esperado,equipamentoRecebido:eq,equipamentoEsperado:esperado});return res.status(409).json({sucesso:false,...ev})}
   if(fluxo.modo==="aguardando_devolucao"){
    const ativos=await ativosFuncionario(fluxo.funcionario.id);const ativo=ativos.find(x=>Number(x.equipamento_id)===Number(eq.id));if(!ativo){const ev=publicar({uid:u,tipo:"sem_emprestimo",mensagem:"Esse equipamento não está emprestado para este funcionário."});limparFluxo();return res.status(409).json({sucesso:false,...ev})}
    const d=await supabase.from("emprestimos").update({data_devolucao:agora(),status:"Devolvido"}).eq("id",ativo.id).is("data_devolucao",null).select().maybeSingle();if(d.error)throw d.error;if(!d.data){limparFluxo();const ev=publicar({uid:u,tipo:"operacao_conflito",mensagem:"A devolução já foi registrada."});return res.status(409).json({sucesso:false,...ev})}
    const up=await supabase.from("equipamentos").update({status:"disponivel"}).eq("id",eq.id);if(up.error)throw up.error;const f=fluxo.funcionario;limparFluxo();const ev=publicar({uid:u,tipo:"devolucao_concluida",modo:"idle",mensagem:`${eq.nome} foi devolvido e está disponível.`,funcionario:f,equipamento:eq,box:eq.box_id});return res.json({sucesso:true,...ev})
   }
   const atual=await supabase.from("equipamentos").select("*").eq("id",eq.id).maybeSingle();if(atual.error)throw atual.error;if(!atual.data||status(atual.data.status)!=="disponivel"){const ev=publicar({uid:u,tipo:"equipamento_emprestado",mensagem:"Esse equipamento já está emprestado."});return res.status(409).json({sucesso:false,...ev})}
   if(await boxOcupada(atual.data.box_id,atual.data.id)){const ev=publicar({uid:u,tipo:"box_ocupada",mensagem:`A Box ${atual.data.box_id} já está ocupada. Uma Box comporta apenas um objeto.`});return res.status(409).json({sucesso:false,...ev})}
   const ativos=await ativosFuncionario(fluxo.funcionario.id);if(ativos.length){const atualEq=await supabase.from("equipamentos").select("*").eq("id",ativos[0].equipamento_id).maybeSingle();if(atualEq.error)throw atualEq.error;const f=fluxo.funcionario;limparFluxo();const ev=publicar({uid:u,tipo:"funcionario_com_emprestimo",mensagem:`Você precisa devolver "${atualEq.data?.nome||"o equipamento"}" antes de pegar outro objeto.`,funcionario:f,equipamento:atualEq.data});return res.status(409).json({sucesso:false,...ev})}
   const ins=await supabase.from("emprestimos").insert([{funcionario_id:Number(fluxo.funcionario.id),equipamento_id:Number(atual.data.id),box:Number(atual.data.box_id),status:"Ativo",data_retirada:agora()}]).select().maybeSingle();if(ins.error)throw ins.error;const up=await supabase.from("equipamentos").update({status:"emprestado"}).eq("id",atual.data.id).eq("status","disponivel").select().maybeSingle();if(up.error)throw up.error;if(!up.data){if(ins.data?.id)await supabase.from("emprestimos").delete().eq("id",ins.data.id);const ev=publicar({uid:u,tipo:"equipamento_emprestado",mensagem:"O equipamento deixou de estar disponível. Tente novamente."});limparFluxo();return res.status(409).json({sucesso:false,...ev})}
   const f=fluxo.funcionario;limparFluxo();const ev=publicar({uid:u,tipo:"retirada_concluida",modo:"idle",mensagem:`${atual.data.nome} está EMPRESTADO para ${f.nome}.`,funcionario:f,equipamento:atual.data,box:atual.data.box_id});return res.status(201).json({sucesso:true,...ev,emprestimo:ins.data})
  }

  const f=await buscarFuncionarioPorUID(u);if(f){const ativos=await ativosFuncionario(f.id);const funcionario={id:f.id,nome:f.nome,matricula:f.matricula,uid_tag_pessoal:f.uid_tag_pessoal};if(ativos.length){const eq=await supabase.from("equipamentos").select("*").eq("id",ativos[0].equipamento_id).maybeSingle();if(eq.error)throw eq.error;fluxo={modo:"aguardando_devolucao",funcionario,acao:"devolucao",equipamentoSelecionado:eq.data||null,expiraEm:Date.now()+120000};const ev=publicar({uid:u,tipo:"funcionario_com_emprestimo",modo:"aguardando_devolucao",mensagem:`${eq.data?.nome||"Equipamento"} está com ${f.nome}. Para continuar, devolva este equipamento antes de pegar outro.`,funcionario,equipamento:eq.data});return res.json({sucesso:true,...ev})}
   const lista=await disponiveis();fluxo={modo:"aguardando_selecao",funcionario,acao:null,equipamentoSelecionado:null,expiraEm:Date.now()+120000};const ev=publicar({uid:u,tipo:"funcionario_identificado",modo:"aguardando_selecao",mensagem:"Funcionário identificado. Selecione o equipamento que deseja retirar.",funcionario,equipamentos:lista});return res.json({sucesso:true,...ev,equipamentos:lista})}
  const eq=await buscarEquipamentoPorUID(u);if(eq){const ev=publicar({uid:u,tipo:"equipamento_sem_funcionario",mensagem:"Passe primeiro a tag do funcionário e selecione o equipamento."});return res.status(409).json({sucesso:false,...ev})}
  const ev=publicar({uid:u,tipo:"tag_nao_cadastrada",mensagem:"TAG NÃO CADASTRADA. Cadastre a tag antes de utilizar."});return res.status(404).json({sucesso:false,...ev})
 }catch(e){return erroResposta(res,e)}
});

app.get("/rfid/ultima",(req,res)=>{expirar();res.set("Cache-Control","no-store,no-cache,must-revalidate,proxy-revalidate");res.json(rfidEvent)});
app.post("/rfid/limpar",(req,res)=>{rfidEvent.nova=false;res.json({sucesso:true})});
app.post("/api/rfid/resetar",(req,res)=>{limparFluxo();cadastroRFID={ativo:false,tipo:null,expiraEm:0};rfidEvent={...rfidEvent,nova:false,id:Date.now(),uid:null,tipo:"idle",modo:"idle",mensagem:"Passe a tag do funcionário.",funcionario:null,equipamento:null,equipamentos:[],momento:Date.now()};res.json({sucesso:true,mensagem:"Operação reiniciada."})});
app.post("/api/rfid/cadastro/iniciar",(req,res)=>{cadastroRFID={ativo:true,tipo:req.body?.tipo==="equipamento"?"equipamento":"funcionario",expiraEm:Date.now()+30000};res.json({sucesso:true,mensagem:"Aguardando uma tag.",tipo:cadastroRFID.tipo})});
app.post("/api/rfid/selecionar",async(req,res)=>{try{expirar();const funcionarioId=Number(req.body?.funcionario_id),equipamentoId=Number(req.body?.equipamento_id),acao=req.body?.acao==="devolucao"?"devolucao":"retirada";if(!Number.isInteger(funcionarioId)||!Number.isInteger(equipamentoId))return res.status(400).json({sucesso:false,erro:"Funcionário ou equipamento inválido."});if(!fluxo.funcionario||Number(fluxo.funcionario.id)!==funcionarioId)return res.status(409).json({sucesso:false,erro:"A identificação expirou. Passe a tag do funcionário novamente."});const e=await supabase.from("equipamentos").select("*").eq("id",equipamentoId).maybeSingle();if(e.error)throw e.error;if(!e.data)return res.status(404).json({sucesso:false,erro:"Equipamento não encontrado."});const ativos=await ativosFuncionario(funcionarioId);
 if(acao==="retirada"){if(ativos.length)return res.status(409).json({sucesso:false,tipo:"funcionario_com_emprestimo",erro:"Você precisa devolver o equipamento que pegou antes de pegar outro."});if(status(e.data.status)!=="disponivel")return res.status(409).json({sucesso:false,erro:"Esse equipamento não está disponível."});if(await boxOcupada(e.data.box_id,e.data.id))return res.status(409).json({sucesso:false,tipo:"box_ocupada",erro:`A Box ${e.data.box_id} já possui um objeto. Uma Box comporta apenas um objeto.`})}
 else{const pertence=ativos.find(x=>Number(x.equipamento_id)===equipamentoId);if(!pertence)return res.status(409).json({sucesso:false,erro:"Esse equipamento não está emprestado para este funcionário."})}
 fluxo={modo:acao==="devolucao"?"aguardando_devolucao":"aguardando_tag_retirada",funcionario:fluxo.funcionario,acao,equipamentoSelecionado:e.data,expiraEm:Date.now()+120000};const ev=publicar({uid:fluxo.funcionario.uid_tag_pessoal,tipo:"equipamento_selecionado",modo:fluxo.modo,mensagem:`Agora passe a tag do equipamento: ${e.data.nome}.`,funcionario:fluxo.funcionario,equipamento:e.data,box:e.data.box_id});return res.json({sucesso:true,...ev})}catch(e){return erroResposta(res,e,400)}});

app.get("/api/funcionarios",async(req,res)=>{try{const r=await supabase.from("funcionarios").select("*").order("id");if(r.error)throw r.error;res.json({sucesso:true,funcionarios:r.data||[]})}catch(e){erroResposta(res,e)}});
app.get("/funcionarios",async(req,res)=>{const r=await supabase.from("funcionarios").select("*").order("id");res.json(r.data||[])});
app.post("/api/funcionarios",async(req,res)=>{try{const nome=texto(req.body?.nome).trim(),matricula=texto(req.body?.matricula).trim(),u=uid(req.body?.uid_tag_pessoal??req.body?.uid_rfid);if(!nome||!matricula||!u)return res.status(400).json({sucesso:false,erro:"Nome, matrícula e UID são obrigatórios."});const ex=await verificarUID(u);if(ex.encontrado)return res.status(409).json({sucesso:false,erro:"Esta tag já está cadastrada."});const r=await supabase.from("funcionarios").insert([{nome,matricula,setor:texto(req.body?.setor).trim()||null,uid_tag_pessoal:u}]).select().single();if(r.error)throw r.error;res.status(201).json({sucesso:true,funcionario:r.data,mensagem:"Funcionário cadastrado."})}catch(e){erroResposta(res,e,400)}});

app.get("/api/equipamentos",async(req,res)=>{try{const r=await supabase.from("equipamentos").select("*").order("id");if(r.error)throw r.error;res.json({sucesso:true,equipamentos:r.data||[]})}catch(e){erroResposta(res,e)}});
app.get("/equipamentos",async(req,res)=>{const r=await supabase.from("equipamentos").select("*").order("id");res.json(r.data||[])});
app.post("/api/equipamentos",async(req,res)=>{try{const nome=texto(req.body?.nome).trim(),u=uid(req.body?.uid_rfid??req.body?.uid_tag),box=Number(req.body?.box??req.body?.box_id);if(!nome||!u||!Number.isInteger(box)||box<1)return res.status(400).json({sucesso:false,erro:"Nome, UID e Box válida são obrigatórios."});const ex=await verificarUID(u);if(ex.encontrado)return res.status(409).json({sucesso:false,erro:"Esta tag já está cadastrada."});if(await boxOcupada(box))return res.status(409).json({sucesso:false,tipo:"box_ocupada",erro:`A Box ${box} já possui um objeto. Uma Box comporta apenas um objeto.`});const r=await supabase.from("equipamentos").insert([{nome,descricao:texto(req.body?.descricao).trim()||null,uid_tag:u,box_id:box,status:"disponivel"}]).select().single();if(r.error)throw r.error;res.status(201).json({sucesso:true,equipamento:r.data,mensagem:"Equipamento cadastrado."})}catch(e){erroResposta(res,e,400)}});
app.put("/api/equipamentos/:id",async(req,res)=>{try{const id=Number(req.params.id),dados={};if(req.body.nome!==undefined)dados.nome=texto(req.body.nome).trim();if(req.body.descricao!==undefined)dados.descricao=req.body.descricao;if(req.body.uid_rfid!==undefined||req.body.uid_tag!==undefined)dados.uid_tag=uid(req.body.uid_rfid??req.body.uid_tag);if(req.body.box!==undefined||req.body.box_id!==undefined){const b=Number(req.body.box??req.body.box_id);if(!Number.isInteger(b)||b<1)return res.status(400).json({sucesso:false,erro:"Box inválida."});if(await boxOcupada(b,id))return res.status(409).json({sucesso:false,erro:`A Box ${b} já possui outro objeto.`});dados.box_id=b}if(req.body.status!==undefined)dados.status=status(req.body.status)==="disponivel"?"disponivel":"emprestado";const r=await supabase.from("equipamentos").update(dados).eq("id",id).select().single();if(r.error)throw r.error;res.json({sucesso:true,equipamento:r.data,mensagem:"Equipamento atualizado."})}catch(e){erroResposta(res,e,400)}});
app.delete("/api/equipamentos/:id",async(req,res)=>{try{const a=await ativoEquipamento(Number(req.params.id));if(a)return res.status(409).json({sucesso:false,erro:"Não é possível excluir um equipamento emprestado."});const r=await supabase.from("equipamentos").delete().eq("id",req.params.id);if(r.error)throw r.error;res.json({sucesso:true,mensagem:"Equipamento excluído."})}catch(e){erroResposta(res,e,400)}});

app.get("/api/emprestimos",async(req,res)=>{try{const r=await supabase.from("emprestimos").select("*").order("id",{ascending:false});if(r.error)throw r.error;res.json({sucesso:true,emprestimos:await enriquecer(r.data||[])})}catch(e){erroResposta(res,e)}});
app.get("/funcionarios/:id",async(req,res)=>{try{const r=await supabase.from("funcionarios").select("*").eq("id",req.params.id).maybeSingle();if(r.error)throw r.error;if(!r.data)return res.status(404).json({sucesso:false,erro:"Funcionário não encontrado."});res.json(r.data)}catch(e){erroResposta(res,e)}});
app.delete("/funcionarios/:id",async(req,res)=>{try{const r=await supabase.from("funcionarios").delete().eq("id",req.params.id);if(r.error)throw r.error;res.json({sucesso:true,mensagem:"Funcionário excluído."})}catch(e){erroResposta(res,e,400)}});
app.post("/funcionarios",async(req,res)=>{try{const nome=texto(req.body?.nome).trim(),matricula=texto(req.body?.matricula).trim(),u=uid(req.body?.uid_tag_pessoal??req.body?.uid_rfid);if(!nome||!matricula||!u)return res.status(400).json({sucesso:false,erro:"Nome, matrícula e UID são obrigatórios."});const ex=await verificarUID(u);if(ex.encontrado)return res.status(409).json({sucesso:false,erro:"Esta tag já está cadastrada."});const r=await supabase.from("funcionarios").insert([{nome,matricula,setor:texto(req.body?.setor).trim()||null,uid_tag_pessoal:u}]).select().single();if(r.error)throw r.error;res.status(201).json({sucesso:true,funcionario:r.data,mensagem:"Funcionário cadastrado."})}catch(e){erroResposta(res,e,400)}});
app.get("/equipamentos/:id",async(req,res)=>{try{const r=await supabase.from("equipamentos").select("*").eq("id",req.params.id).maybeSingle();if(r.error)throw r.error;if(!r.data)return res.status(404).json({sucesso:false,erro:"Equipamento não encontrado."});res.json(r.data)}catch(e){erroResposta(res,e)}});
app.post("/equipamentos",async(req,res)=>{try{const nome=texto(req.body?.nome).trim(),u=uid(req.body?.uid_rfid??req.body?.uid_tag),box=Number(req.body?.box??req.body?.box_id);if(!nome||!u||!Number.isInteger(box)||box<1)return res.status(400).json({sucesso:false,erro:"Nome, UID e Box válida são obrigatórios."});const ex=await verificarUID(u);if(ex.encontrado)return res.status(409).json({sucesso:false,erro:"Esta tag já está cadastrada."});if(await boxOcupada(box))return res.status(409).json({sucesso:false,tipo:"box_ocupada",erro:`A Box ${box} já possui um objeto. Uma Box comporta apenas um objeto.`});const r=await supabase.from("equipamentos").insert([{nome,descricao:texto(req.body?.descricao).trim()||null,uid_tag:u,box_id:box,status:"disponivel"}]).select().single();if(r.error)throw r.error;res.status(201).json({sucesso:true,equipamento:r.data,mensagem:"Equipamento cadastrado."})}catch(e){erroResposta(res,e,400)}});
app.delete("/equipamentos/:id",async(req,res)=>{try{const a=await ativoEquipamento(Number(req.params.id));if(a)return res.status(409).json({sucesso:false,erro:"Não é possível excluir um equipamento emprestado."});const r=await supabase.from("equipamentos").delete().eq("id",req.params.id);if(r.error)throw r.error;res.json({sucesso:true,mensagem:"Equipamento excluído."})}catch(e){erroResposta(res,e,400)}});

app.get("/api/ultimos-emprestimos",async(req,res)=>{try{const r=await supabase.from("emprestimos").select("*").order("id",{ascending:false}).limit(10);if(r.error)throw r.error;res.json({sucesso:true,emprestimos:await enriquecer(r.data||[])})}catch(e){erroResposta(res,e)}});
app.get("/emprestimos",async(req,res)=>{try{const r=await supabase.from("emprestimos").select("*").order("id",{ascending:false});if(r.error)throw r.error;const rows=await enriquecer(r.data||[]);res.json(rows.map(x=>({...x,funcionario:x.funcionario?.nome||"-",matricula:x.funcionario?.matricula||"-",equipamento:x.equipamento?.nome||"-",box_id:x.equipamento?.box_id??x.box??"-"})))}catch(e){erroResposta(res,e)}});
app.get("/api/dashboard",async(req,res)=>{try{const fs=await supabase.from("funcionarios").select("id",{count:"exact",head:true}),es=await supabase.from("equipamentos").select("id,status,box_id"),ls=await supabase.from("emprestimos").select("id").is("data_devolucao",null);if(fs.error)throw fs.error;if(es.error)throw es.error;if(ls.error)throw ls.error;const eq=es.data||[];res.json({sucesso:true,funcionarios:fs.count||0,equipamentos:eq.length,disponiveis:eq.filter(x=>status(x.status)==="disponivel").length,emprestimos:(ls.data||[]).length,emprestados:(ls.data||[]).length})}catch(e){erroResposta(res,e)}});

app.use((req,res)=>res.status(404).json({sucesso:false,erro:"Rota não encontrada",rota:req.originalUrl}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({sucesso:false,erro:"Erro interno do servidor."})});

(async()=>{await corrigirBoxesDuplicadas();app.listen(PORT,"0.0.0.0",()=>console.log(`INVENTÁRIO RFID - NUVEM | porta ${PORT} | aguardando ESP32...`))})().catch(e=>{console.error(e);process.exit(1)});
